-- PostgreSQL foundation for the production adapter, not connected to the application yet.
-- Transactional, idempotent bootstrap. No real personal data. Internal schema not exposed by Supabase Data API.
BEGIN;
CREATE SCHEMA IF NOT EXISTS ec;
CREATE TABLE IF NOT EXISTS ec.agencies (id text PRIMARY KEY, name text NOT NULL, address jsonb NOT NULL DEFAULT '{}', truth_status text NOT NULL CHECK(truth_status IN ('OBSERVÉ','PROPOSÉ','À_CONFIRMER','VALIDÉ')), validated_by uuid, validated_at timestamptz);
CREATE TABLE IF NOT EXISTS ec.organizations (id uuid PRIMARY KEY, name text NOT NULL);
CREATE TABLE IF NOT EXISTS ec.memberships (user_id uuid NOT NULL, organization_id uuid REFERENCES ec.organizations(id), agency_id text REFERENCES ec.agencies(id), role text NOT NULL CHECK(role IN ('admin','manager','agent','sales','finance','client')), PRIMARY KEY(user_id,role));
CREATE TABLE IF NOT EXISTS ec.quotes (id uuid PRIMARY KEY, reference text UNIQUE NOT NULL, idempotency_key uuid UNIQUE NOT NULL, fingerprint text NOT NULL, owner_id uuid, agency_id text REFERENCES ec.agencies(id), payload jsonb NOT NULL, volume numeric(30,18) NOT NULL CHECK(volume>0), status text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS ec.tariff_rules (id uuid PRIMARY KEY, version integer NOT NULL, service text NOT NULL, route text NOT NULL, category text NOT NULL, currency text NOT NULL CHECK(currency IN ('EUR','XAF')), rules jsonb NOT NULL, truth_status text NOT NULL, valid_from timestamptz, valid_to timestamptz, UNIQUE(id,version));
CREATE TABLE IF NOT EXISTS ec.proposals (id uuid PRIMARY KEY, quote_id uuid NOT NULL REFERENCES ec.quotes(id), version integer NOT NULL, number text UNIQUE NOT NULL, currency text NOT NULL, total_minor bigint NOT NULL CHECK(total_minor>=0), tariff_snapshot jsonb, exclusions text NOT NULL, valid_until timestamptz, accepted_at timestamptz, UNIQUE(quote_id,version));
CREATE TABLE IF NOT EXISTS ec.parcels (id uuid PRIMARY KEY, reference text UNIQUE NOT NULL, quote_id uuid REFERENCES ec.quotes(id), declared jsonb NOT NULL, controlled jsonb, reserves text, checked_by uuid, checked_at timestamptz);
CREATE TABLE IF NOT EXISTS ec.departures (id uuid PRIMARY KEY, mode text NOT NULL CHECK(mode IN ('aerien','maritime')), scheduled_at timestamptz, confirmed_at timestamptz, agency_id text REFERENCES ec.agencies(id), status text NOT NULL);
CREATE TABLE IF NOT EXISTS ec.shipments (id uuid PRIMARY KEY, owner_id uuid NOT NULL, agency_id text NOT NULL REFERENCES ec.agencies(id), route text NOT NULL CHECK(route='FR-CG'), service text NOT NULL, public_reference text UNIQUE NOT NULL, departure_id uuid REFERENCES ec.departures(id), status text NOT NULL);
CREATE TABLE IF NOT EXISTS ec.assignments (parcel_id uuid PRIMARY KEY REFERENCES ec.parcels(id), shipment_id uuid NOT NULL REFERENCES ec.shipments(id));
CREATE TABLE IF NOT EXISTS ec.events (id uuid PRIMARY KEY, shipment_id uuid NOT NULL REFERENCES ec.shipments(id), status text NOT NULL, occurred_at timestamptz NOT NULL, location text NOT NULL, actor_id uuid NOT NULL, source text NOT NULL, public boolean NOT NULL DEFAULT false, corrects_id uuid REFERENCES ec.events(id));
CREATE TABLE IF NOT EXISTS ec.documents (id uuid PRIMARY KEY, owner_id uuid NOT NULL, quote_id uuid REFERENCES ec.quotes(id), shipment_id uuid REFERENCES ec.shipments(id), private_path text UNIQUE NOT NULL, mime text NOT NULL CHECK(mime IN ('application/pdf','image/png','image/jpeg')), scan_status text NOT NULL DEFAULT 'quarantine', version integer NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS ec.payments (id uuid PRIMARY KEY, proposal_id uuid NOT NULL REFERENCES ec.proposals(id), provider text NOT NULL, provider_reference text NOT NULL, amount_minor bigint NOT NULL CHECK(amount_minor>0), currency text NOT NULL, state text NOT NULL, reconciled_by uuid, UNIQUE(provider,provider_reference));
CREATE TABLE IF NOT EXISTS ec.notifications (id uuid PRIMARY KEY, dedup_key text UNIQUE NOT NULL, recipient_id uuid NOT NULL, channel text NOT NULL, state text NOT NULL, attempts integer NOT NULL DEFAULT 0, next_attempt_at timestamptz, last_error text);
CREATE TABLE IF NOT EXISTS ec.tickets (id uuid PRIMARY KEY, owner_id uuid NOT NULL, shipment_id uuid REFERENCES ec.shipments(id), subject text NOT NULL, state text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS ec.content (slug text NOT NULL, version integer NOT NULL, body jsonb NOT NULL, truth_status text NOT NULL, validated_by uuid, validated_at timestamptz, PRIMARY KEY(slug,version));
CREATE TABLE IF NOT EXISTS ec.audit (id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY, actor_id uuid, action text NOT NULL, object_id text NOT NULL, detail jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
-- Fail closed until an authenticated repository and scoped policies have been tested.
DO $$ DECLARE item record; BEGIN FOR item IN SELECT tablename FROM pg_tables WHERE schemaname='ec' LOOP EXECUTE format('ALTER TABLE ec.%I ENABLE ROW LEVEL SECURITY',item.tablename); EXECUTE format('ALTER TABLE ec.%I FORCE ROW LEVEL SECURITY',item.tablename); EXECUTE format('REVOKE ALL ON ec.%I FROM PUBLIC',item.tablename); END LOOP; END $$;
REVOKE ALL ON SCHEMA ec FROM PUBLIC;
COMMIT;
